INSERT INTO PUBLIC.COUNTRY (ID, COUNTRY_NAME, COUNTRY_CODE, START_DATE, END_DATE) VALUES (101, 'Ukraine', 'UKR', '2014-09-09', null);
INSERT INTO PUBLIC.COUNTRY (ID, COUNTRY_NAME, COUNTRY_CODE, START_DATE, END_DATE) VALUES (102, 'Japan', 'JPN', '2014-09-09', null);
INSERT INTO PUBLIC.COUNTRY (ID, COUNTRY_NAME, COUNTRY_CODE, START_DATE, END_DATE) VALUES (6700, 'The United States', 'USA', '2014-10-03', null);
INSERT INTO PUBLIC.COUNTRY (ID, COUNTRY_NAME, COUNTRY_CODE, START_DATE, END_DATE) VALUES (6751, 'Netherlands', 'NLD', '2014-10-03', null);
INSERT INTO PUBLIC.COUNTRY (ID, COUNTRY_NAME, COUNTRY_CODE, START_DATE, END_DATE) VALUES (6800, 'Island', 'ISL', '2014-10-06', null);
INSERT INTO PUBLIC.COUNTRY (ID, COUNTRY_NAME, COUNTRY_CODE, START_DATE, END_DATE) VALUES (6850, 'Afganistan', 'AFG', '2014-10-06', null);