INSERT INTO PUBLIC.OPERATOR_PRODUCT (FK_OPERATOR, FK_PRODUCT) VALUES (5050, 5500);
INSERT INTO PUBLIC.OPERATOR_PRODUCT (FK_OPERATOR, FK_PRODUCT) VALUES (5050, 5051);
INSERT INTO PUBLIC.OPERATOR_PRODUCT (FK_OPERATOR, FK_PRODUCT) VALUES (5050, 5050);
INSERT INTO PUBLIC.OPERATOR_PRODUCT (FK_OPERATOR, FK_PRODUCT) VALUES (5050, 5550);
INSERT INTO PUBLIC.OPERATOR_PRODUCT (FK_OPERATOR, FK_PRODUCT) VALUES (5350, 5500);
INSERT INTO PUBLIC.OPERATOR_PRODUCT (FK_OPERATOR, FK_PRODUCT) VALUES (5350, 5050);
INSERT INTO PUBLIC.OPERATOR_PRODUCT (FK_OPERATOR, FK_PRODUCT) VALUES (5350, 5550);
INSERT INTO PUBLIC.OPERATOR_PRODUCT (FK_OPERATOR, FK_PRODUCT) VALUES (5350, 5051);